#print("Hello World")
# print("this Is Sagol")
# print('This is','Sagor')
# print('This is', 'Hasmir',sep='---')
print(" Hello Lia")
print("this is Mula")
print('This is','mula')
print('this is ','Hasmir',sep='---')
print('rubel','nayem',sep='+++')